stages:
- name: stage01
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: alexk8sapp01
      registry: index.docker.io
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: alexk8sapp01
      registry: index.docker.io
timeout: 60
notification: {}
